ckfinder:
  enabled: false
  base-dir:
  base-url:
  license-key:
  license-name:
  img-width: 1600
  img-height: 1200
  img-quality: 0.8
  default-resource-types:
  types:
    - name: Files
      url: '%BASE_URL%files/'
      directory: '%BASE_DIR%/files'
      maxSize: 0
      allowedExtensions: 7z,aiff,asf,avi,bmp,csv,doc,docx,fla,flv,gif,gz,gzip,jpeg,jpg,mid,mov,mp3,mp4,mpc,mpeg,mpg,ods,odt,pdf,png,ppt,pptx,pxd,qt,ram,rar,rm,rmi,rmvb,rtf,sdc,sitd,swf,sxc,sxw,tar,tgz,tif,tiff,txt,vsd,wav,wma,wmv,xls,xlsx,zip
      deniedExtensions: exe,jsp,jspx,asp,aspx
    - name: Images
      url: '%BASE_URL%images/'
      directory: '%BASE_DIR%/images'
      maxSize: 0
      allowedExtensions: bmp,gif,jpeg,jpg,png
      deniedExtensions:
#    - name: Flash
#      url: '%BASE_URL%flash/'
#      directory: '%BASE_DIR%/flash'
#      maxSize: 0
#      allowedExtensions: swf,flv
#      deniedExtensions:
  user-role-session-var:
  access-controls:
  - role: '*'
    resourceType: '*'
    folder: /
    folderView: true
    folderCreate: true
    folderRename: true
    folderDelete: true
    fileView: true
    fileUpload: true
    fileRename: true
    fileDelete: true
  thumbs:
    enabled: true
    url: '%BASE_URL%_thumbs/'
    directory: '%BASE_DIR%/_thumbs'
    direct-access: false
    max-height: 100
    max-width: 100
    quality: 0.8
  disallow-unsafe-characters: false
  check-double-extension: true
  check-size-after-scaling: true
  secure-image-uploads: true
  html-extensions: html,htm,xml,js
  force-ascii: false
  enable-csrf-protection: true
  hide-folders:
  hide-files:
