language: java
before_cache:
- mvn build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
  - $HOME/.m2
jdk: oraclejdk8
install: true
script: source .travis/publish.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
